newcm

diff --git a/bin/todo b/bin/todo
--- a/bin/todo
+++ b/bin/todo
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-VERSION=1.0.1
-VERDATE="August 06, 2026"
+VERSION=1.2
+VERDATE="August 24, 2026"
 
-todoDir="$HOME/.config/todo"
+todoDir="$HOME/folders/text"
 todoLocation="${todoDir}/todo.txt"
 
 FORMAT="\033["
@@ -13,15 +13,7 @@ ESC="m"
 NC="${FORMAT}0$ESC"
 BOLD="${FORMAT}1${ESC}"
 RED="${FORMAT}0;31$ESC"
-YELLOW="${FORMAT}0;33$ESC"
-GREEN="${FORMAT}0;32$ESC"
-BLUE="${FORMAT}0;34$ESC"
-MAGENTA="${FORMAT}0;35$ESC"
-
-WARN="${YELLOW}[WARN]${NC}"
 ERROR="${RED}[ERROR]${NC}"
-INFO="${BLUE}[INFO]${NC}"
-PROMPT="${MAGENTA}[PROMPT]${NC}"
 
 usage() {
     printf "%b\n" "
@@ -29,25 +21,27 @@ ${BOLD}todo${NC} [-l]
     a personal todo list tool
 
 ${BOLD}usage${NC}
-    --help      -h          print help
-    --version   -v          print version
-    --add       -a  <item>  add to todo list
-    --delete    -d  <index> remove from todo list
-    --list      -l          list all of todo
+    --help      -h                      print help
+    --version   -v                      print version
+    --add       -a  <item>              add to todo list
+    --delete    -d  <index>             remove from todo list
+    --edit      -e  <index> <newitem>   edit existing item
+    --list      -l                      list all of todo
+    --reset     -r                      clear todo
 "
 }
 
 ver() {
     printf "%b\n" "
-todo ${BOLD}${VER}${NC} ${VERDATE}
+todo ${BOLD}${VERSION}${NC} ${VERDATE}
 "
 }
 
 error() {
     local msg=$1
     local exitCode=${2:-1}
-    printf "%b\n" "${ERROR} ${msg}; exiting code $exitCode" &>2
-    exit $exitCode
+    printf "%b\n" "${ERROR} ${msg}; exiting code $exitCode" >&2
+    exit "$exitCode"
 }
 
 # make file
@@ -61,12 +55,10 @@ addTodoItem() {
 }
 
 delTodoItemIndex() {
-    for index in "${del[@]}"; do
+    for index in $(printf '%s\n' "${del[@]}" | sort -nr); do
         sed -i "${index}d" "$todoLocation"
     done
 }
-
-# cat "$todoLocation"
 
 while (($#)); do
     case "$1" in
@@ -79,6 +71,7 @@ while (($#)); do
             shift
             while (($#)) && [[ $1 != -* ]]; do add+=("$1")
             shift; done;
+            # echo "${add[@]}"
             addTodoItem
             continue;;
         -d|--delete)
@@ -86,14 +79,31 @@ while (($#)); do
             shift
             while (($#)) && [[ $1 != -* ]] && [[ $1 =~ ^[1-9][0-9]*$ ]]; do del+=("$1")
             shift; done;
+            # echo "${del[@]}"
             delTodoItemIndex
             continue;;
-        -l|--list|*)
+        -l|--list)
             i=1
             while IFS= read -r line; do
                 printf "%b%2d.%b %s\n" "$BOLD" "$i" "$NC" "$line"
-                ((i++))
+                ((++i))
             done < "$todoLocation"
+            ;;
+        -e|--edit)
+
+            shift
+            index="$1"
+            shift
+            edititem="$1"
+
+            sed -i "${index}c\\${edititem}" "$todoLocation"
+            ;;
+        -r|--reset)
+            newTodo="/tmp/todo.txt"
+            touch "$newTodo"
+            if mv "$newTodo" "$todoLocation"; then
+                echo "reset"
+            fi
             ;;
         -*)
             error "unknown parameter $1";;
